export const generos = [
  "Romance",
  "Religião e Mitologia",
  "Ficção Científica",
  "Arte e Cultura",
  "Fantasia",
  "Biografias e Memórias",
  "Thriller e Mistério",
  "Quadrinhos e Mangá",
  "Terror",
  "Infantojuvenil",
  "Aventura",
  "Ciência e Conhecimento",
  "Poesia e Crônicas",
  "História",
  "Guia, Manual e Gastronomia",
  "Política",
  "Autoajuda e Desenvolvimento Pessoal",
  "Economia",
  "Literatura",
] as const;
